// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeMasterPassword(arg1, arg2) {
  return window['go']['main']['App']['ChangeMasterPassword'](arg1, arg2);
}

export function DeleteCredential(arg1) {
  return window['go']['main']['App']['DeleteCredential'](arg1);
}

export function GetCredential(arg1) {
  return window['go']['main']['App']['GetCredential'](arg1);
}

export function GetCredentialsByProvider(arg1) {
  return window['go']['main']['App']['GetCredentialsByProvider'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsMasterPasswordSetup() {
  return window['go']['main']['App']['IsMasterPasswordSetup']();
}

export function IsVaultLocked() {
  return window['go']['main']['App']['IsVaultLocked']();
}

export function ListCredentials() {
  return window['go']['main']['App']['ListCredentials']();
}

export function LockVault() {
  return window['go']['main']['App']['LockVault']();
}

export function SetupMasterPassword(arg1) {
  return window['go']['main']['App']['SetupMasterPassword'](arg1);
}

export function StoreCredential(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StoreCredential'](arg1, arg2, arg3, arg4);
}

export function UnlockVault(arg1) {
  return window['go']['main']['App']['UnlockVault'](arg1);
}

export function UpdateCredential(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateCredential'](arg1, arg2, arg3, arg4, arg5);
}
