// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function ChangeMasterPassword(arg1:string,arg2:string):Promise<void>;

export function DeleteCredential(arg1:number):Promise<void>;

export function GetCredential(arg1:number):Promise<models.Credential>;

export function GetCredentialsByProvider(arg1:number):Promise<Array<models.Credential>>;

export function Greet(arg1:string):Promise<string>;

export function IsMasterPasswordSetup():Promise<boolean>;

export function IsVaultLocked():Promise<boolean>;

export function ListCredentials():Promise<Array<models.Credential>>;

export function LockVault():Promise<void>;

export function SetupMasterPassword(arg1:string):Promise<void>;

export function StoreCredential(arg1:number,arg2:string,arg3:string,arg4:string):Promise<number>;

export function UnlockVault(arg1:string):Promise<void>;

export function UpdateCredential(arg1:number,arg2:number,arg3:string,arg4:string,arg5:string):Promise<void>;
